spring:
  profiles:
    active: 'dev'
  application:
    name: account-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mainDb
      uri: mongodb://localhost:27017/mainDb

server:
  port: 8501
  compression:
    enabled: true
    mime-types: application/json

# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO